In [2]:
first_list=[2,3,4,5]
print(map(lambda x: x**2 ,first_list))
print(list(map(lambda x: x**2, first_list)))

[4, 9, 16, 25]


In [4]:
def squareit(n):
    return n**2
print(list(map(squareit,first_list)))

[4, 9, 16, 25]


In [5]:
sum_list1=[1,2,3,4]
sum_list2=[5,6,7,8]
print(list(map(lambda x,y : x+y , sum_list1,sum_list2)))

[6, 8, 10, 12]


In [6]:
names1=['nikola','james','albert']
names2=['tesla','watt','einstein']
proper=lambda x,y : x[0].upper()+x[1:]+' '+y[0].upper()+y[1:]
print(list(map(proper,names1,names2)))

['Nikola Tesla', 'James Watt', 'Albert Einstein']


In [1]:
#filter
divby3=lambda x: x%3==0
my_list=[3,4,5,6,7,8,9]
div=filter(divby3,my_list)
print(list(div))

[3, 6, 9]


In [2]:
m_list=[1,2,3,4,5]
m_filter=lambda x: x>3
output=filter(m_filter,m_list)
print(list(output))

[4, 5]


In [6]:
#Reduce
from functools import reduce
q=reduce(lambda x,y:x+y,range(1,4))
print(q)
##ULTIMATELY PRINTS SUM OF ELEMENTS OF LIST I.E.1 ,2 ,3.

6


In [7]:
from functools import reduce
q=reduce(lambda x,y:x+y,[47,11,42,13])
print(q)
###ULTIMATELY PRINTS SUM OF ELEMENTS OF LIST.

113


In [10]:
LIST_OF_NUMS=[22,45,32,20,87,988,30]
print(reduce(lambda x,y: x if x>y else y , LIST_OF_NUMS))
###PRINTS LARGEST ELEMENT OF THE LIST.

988


In [11]:
import numpy as np
array_1=np.array([1,2,3,4])
print(array_1)
array_2=np.array([[1,2,3,4],[5,6,7]])
print(array_2)

[1 2 3 4]
[list([1, 2, 3, 4]) list([5, 6, 7])]


C:\Users\Dell\AppData\Local\Temp/ipykernel_11228/2987809512.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_2=np.array([[1,2,3,4],[5,6,7]])


In [14]:
d1_array=np.array([2,4,5,6,7,9])
print(d1_array)
print(type(d1_array))

[2 4 5 6 7 9]
<class 'numpy.ndarray'>


In [15]:
d2_array=np.array([[2,3,4],[5,8,7]])
print(d2_array)

[[2 3 4]
 [5 8 7]]


In [17]:
list_1=[1,2,3,4]
list_2=[5,6,7,8]
product_list=list(map(lambda x,y: x*y,list_1,list_2))
print(product_list)##printing products of corresponding elements of list.

[5, 12, 21, 32]


In [21]:
import numpy as np
array_1=np.array([1,2,3,4])
array_2=np.array([5,6,7,8])
array_3=array_1*array_2
print(array_3)##by Numpy
print(type(array_3))

[ 5 12 21 32]
<class 'numpy.ndarray'>


In [23]:
list_squared=[i**2 for i in list_1]
array_squared=array_1**2
print(list_squared)## here commas in output as it is a list.
print(array_squared)##here no commas in ouptut as it is an array.

[1, 4, 9, 16]
[ 1  4  9 16]


In [24]:
array_from_list=np.array([2,5,6,7])
array_from_tuple=np.array([4,5,8,9])
print(array_from_list)
print(array_from_tuple)

[2 5 6 7]
[4 5 8 9]


In [28]:
np.ones((5,3))
#print(type(np.ones((5,3))))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((5,3),dtype=np.int)

C:\Users\Dell\AppData\Local\Temp/ipykernel_11228/2725301509.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones((5,3),dtype=np.int)


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [30]:
np.zeros((4,3),dtype=np.int)

C:\Users\Dell\AppData\Local\Temp/ipykernel_11228/2027068723.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((4,3),dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [2]:
import numpy as np
np.random.random([3,4])

array([[0.21237193, 0.29671984, 0.83526821, 0.61601299],
       [0.27687338, 0.62895051, 0.11680293, 0.49157493],
       [0.12046319, 0.95517219, 0.82639687, 0.65319419]])

In [5]:
numbers=np.arange(10,100,5)
print(numbers)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [6]:
#print 100 numbers between 5 and 6.
np.linspace(5,6,100)

array([5.        , 5.01010101, 5.02020202, 5.03030303, 5.04040404,
       5.05050505, 5.06060606, 5.07070707, 5.08080808, 5.09090909,
       5.1010101 , 5.11111111, 5.12121212, 5.13131313, 5.14141414,
       5.15151515, 5.16161616, 5.17171717, 5.18181818, 5.19191919,
       5.2020202 , 5.21212121, 5.22222222, 5.23232323, 5.24242424,
       5.25252525, 5.26262626, 5.27272727, 5.28282828, 5.29292929,
       5.3030303 , 5.31313131, 5.32323232, 5.33333333, 5.34343434,
       5.35353535, 5.36363636, 5.37373737, 5.38383838, 5.39393939,
       5.4040404 , 5.41414141, 5.42424242, 5.43434343, 5.44444444,
       5.45454545, 5.46464646, 5.47474747, 5.48484848, 5.49494949,
       5.50505051, 5.51515152, 5.52525253, 5.53535354, 5.54545455,
       5.55555556, 5.56565657, 5.57575758, 5.58585859, 5.5959596 ,
       5.60606061, 5.61616162, 5.62626263, 5.63636364, 5.64646465,
       5.65656566, 5.66666667, 5.67676768, 5.68686869, 5.6969697 ,
       5.70707071, 5.71717172, 5.72727273, 5.73737374, 5.74747

In [7]:
##creating 4X3 array of 7s using np.full()
#the default datatype is int only.
np.full((4,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [8]:
##np.tile() creates a new array by repeating the given array any number of times you want.
#default datatype is int.
arr=([0,1,2])
np.tile(arr,3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [9]:
#creating multidimensional array.
np.tile(arr,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [10]:
##creating 3X3 identity matrix using np.eye()
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [79]:
np.random.randint(0,10,(4,4))##4X4 random array of integers ranging from 0 to 9.

array([[0, 6, 8, 5],
       [6, 6, 4, 1],
       [6, 7, 4, 3],
       [6, 1, 3, 3]])

In [80]:
rand_array=np.random.random((1000,300))##random 1000X300 array
print(rand_array)

[[0.69876648 0.32391448 0.4928405  ... 0.55836073 0.99972699 0.38860969]
 [0.29374798 0.70438771 0.28341029 ... 0.39930713 0.55155485 0.54476892]
 [0.06629505 0.71879272 0.56148644 ... 0.06266883 0.05278077 0.86377738]
 ...
 [0.61174276 0.60051426 0.56961432 ... 0.03927002 0.06550821 0.96820226]
 [0.77813464 0.63576308 0.40488661 ... 0.34215667 0.93914704 0.05061327]
 [0.73760839 0.16976646 0.76829234 ... 0.99152167 0.9058574  0.38664792]]


In [82]:
print(rand_array[1,])##printing 2nd row.

[2.93747981e-01 7.04387713e-01 2.83410285e-01 3.69824915e-01
 1.33795582e-03 2.12839412e-01 3.60440753e-01 8.90577965e-01
 5.64681835e-02 1.16094900e-01 8.76996207e-01 4.52397196e-01
 8.36206679e-01 3.39894080e-01 2.32138040e-01 1.96985703e-01
 9.02163824e-01 2.86376773e-01 3.35525077e-01 7.99136649e-02
 8.11894760e-01 6.68332264e-02 3.74858046e-01 7.62101212e-01
 1.64611962e-01 5.06850879e-02 6.27500640e-01 4.50745991e-01
 7.61771594e-01 8.09428759e-01 9.32655550e-01 3.81161893e-01
 1.59020369e-01 8.38921378e-01 1.81150688e-01 8.99020729e-01
 2.64323080e-01 5.99128757e-01 7.96545353e-01 8.05638365e-01
 2.60237973e-01 5.49318101e-01 2.00390548e-01 2.10537687e-01
 3.89018155e-01 8.87613316e-01 1.06943718e-01 9.93110977e-01
 2.16033846e-01 1.36922837e-01 9.84055074e-01 3.84070244e-01
 3.29928260e-01 2.81403494e-01 1.64771635e-01 4.17956902e-01
 9.29702569e-01 8.53143748e-01 7.46891243e-01 6.09692994e-01
 5.95954912e-01 2.38187537e-01 6.85912890e-01 1.38609366e-01
 1.39218036e-01 4.245096

In [84]:
print(rand_array[0,2])##(0,2) th element printed.

0.49284049522608686


In [86]:
print("SHAPE:{}".format(rand_array.shape))
print("dtype:{}".format(rand_array.dtype))
print("dimensions:{}".format(rand_array.ndim))
print("itemsize:{}".format(rand_array.itemsize))

SHAPE:(1000, 300)
dtype:float64
dimensions:2
itemsize:8


In [95]:
array_1d=np.arange(10)
print(array_1d)
print(array_1d[2])
print(array_1d[[2,5,6]])##gives elements at indices 2,5 and 6
print(array_1d[2:])
print(array_1d[:3])
print(array_1d[2:7])
print(array_1d[0::2])

[0 1 2 3 4 5 6 7 8 9]
2
[2 5 6]
[2 3 4 5 6 7 8 9]
[0 1 2]
[2 3 4 5 6]
[0 2 4 6 8]


In [97]:
#iterations are similar to lists.
for i in array_1d:
    print(i**2)

0
1
4
9
16
25
36
49
64
81


In [98]:
array_2d=np.array([[2,5,7,5],[4,6,8,10],[10,12,15,19]])
print(array_2d)

[[ 2  5  7  5]
 [ 4  6  8 10]
 [10 12 15 19]]


In [99]:
#print 3rd row 2nd column
print(array_2d[2,1])

12


In [101]:
#slicing the 2nd row and all columns.
#resultant is 1d array.
print(array_2d[1,:])
print(type(array_2d[1,:]))

[ 4  6  8 10]
<class 'numpy.ndarray'>


In [102]:
#slicing all rows and 3rd column.
print(array_2d[:,2])

[ 7  8 15]


In [104]:
#slicing all rows and the first three columns.
print(array_2d[:,:3])

[[ 2  5  7]
 [ 4  6  8]
 [10 12 15]]


In [105]:
#iterating over 2d arrays
for row in array_2d:
    print(row)

[2 5 7 5]
[ 4  6  8 10]
[10 12 15 19]


In [106]:
#iterating over 3d arrays: done with respect to first axis.
array_3d=np.arange(24).reshape(2,3,4)
print(array_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [108]:
for row in array_3d:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [113]:
#comparing time taken for computation.
list1=[i for i in range(1000000)]
list2=[j**2 for j in range(1000000)]
import time
#list multiplication
t0=time.time()
product_list=list(map(lambda x,y:x*y,list1,list2))
t1=time.time()
list_time=t1-t0
print(t1-t0)
#numpy array multiplication
array_1=np.array(list1)
array_2=np.array(list2)
t0=time.time()
array_3=array_1*array_2
t1=time.time()
numpy_time=t1-t0
print(t1-t0)
print("The ratio of time taken is {}".format(list_time/numpy_time))
#By result we see numpy is an order of magnitude faster than lists.

0.5549709796905518
0.014002561569213867
The ratio of time taken is 39.63353254669595


In [115]:
some_array0=np.arange(0,12)#1d array 
print(some_array0)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [116]:
#reshaping 1d array to 3X4 array.
some_array=np.arange(0,12).reshape(3,4)
print(some_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [118]:
arr1=np.arange(0,4).reshape(2,2)
print(arr1)
print(arr1.T)#transpose of matrix

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]


In [119]:
some_array.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [120]:
some_array.reshape(4,-1)# -1 means whatever dimension is needed and dimensions are calculated automatically.

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [121]:
array_1=np.arange(12).reshape(3,4)
array_2=np.arange(20).reshape(5,4)
print(array_1)
print("\n")
print(array_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [122]:
#for horizontal stacking no. of rows should be same while for verical stacking no. of columns should be same.
#above no. of columns are same.so vertical stacking can be done.
np.vstack((array_1,array_2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [123]:
array_1=np.arange(12).reshape(3,4)
array_2=np.arange(15).reshape(3,5)
print(array_1)
print("\n")
print(array_2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [125]:
np.hstack((array_1,array_2))# as no. of rows are same.

array([[ 0,  1,  2,  3,  0,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  5,  6,  7,  8,  9],
       [ 8,  9, 10, 11, 10, 11, 12, 13, 14]])

In [127]:
a=np.arange(1,20)
print(a)
print("\n")
print(np.sin(a))
print("\n")
print(np.cos(a))
print("\n")
print(np.exp(a))
print("\n")
print(np.log(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021 -0.53657292
  0.42016704  0.99060736  0.65028784 -0.28790332 -0.96139749 -0.75098725
  0.14987721]


[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257   0.84385396
  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334  0.66031671
  0.98870462]


[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05
 4.42413392e+05 1.20260428e+06 3.26901737e+06 8.88611052e+06
 2.41549528e+07 6.56599691e+07 1.78482301e+08]


[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527 2.48490665
 2.56494936 2.63905733 2.7080502  2.7725887

In [128]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [130]:
# calculating x/x+1 for each element of array.
a_list=[x/(x+1) for x in a]
print(a_list)#non-numpy method

[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9, 0.9090909090909091, 0.9166666666666666, 0.9230769230769231, 0.9285714285714286, 0.9333333333333333, 0.9375, 0.9411764705882353, 0.9444444444444444, 0.9473684210526315, 0.95]


In [131]:
#The numpy way : vectorise the function, then apply it.
f=np.vectorize(lambda x: x/(x+1))
f(a)

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333,
       0.85714286, 0.875     , 0.88888889, 0.9       , 0.90909091,
       0.91666667, 0.92307692, 0.92857143, 0.93333333, 0.9375    ,
       0.94117647, 0.94444444, 0.94736842, 0.95      ])

In [133]:
# apply function on 2d array:applied to each element
b=np.linspace(1,100,10)# prints 10 numbers between 1 and 100.
print(b)
f(b)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


array([0.5       , 0.92307692, 0.95833333, 0.97142857, 0.97826087,
       0.98245614, 0.98529412, 0.98734177, 0.98888889, 0.99009901])

In [136]:
# advantage is when we vectorize a function one we can apply it as many times as possible.

In [143]:
##np.linalg---> to apply common linear algebra.
##np.linalg.inv---->inverse of matrix.
##np.linalg.det---->determinant of matrix
##np.linalg.eig---->eigen values of a matrix

In [141]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,13).reshape(3,4)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [142]:
np.linalg.inv(a)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [144]:
np.linalg.det(a)

6.66133814775094e-16

In [145]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -4.22209278e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [148]:
import pandas as pd
import numpy as np
s=pd.Series([2,4,5,6,9])#numeric panda series.
print(s)
print(type(s))

0    2
1    4
2    5
3    6
4    9
dtype: int64
<class 'pandas.core.series.Series'>


In [152]:
char_species=pd.Series(['a','b','af'])#creating a series of characters
char_species
print(char_species)
num=pd.Series([1,2,3,4,5,6])
print(num)

0     a
1     b
2    af
dtype: object
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [155]:
date_series=pd.date_range(start='11-09-2021',end='12-12-2021')# creating series of type datetime
print(type(date_series))
print(date_series)
# output is of form "year-month-date".

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
DatetimeIndex(['2021-11-09', '2021-11-10', '2021-11-11', '2021-11-12',
               '2021-11-13', '2021-11-14', '2021-11-15', '2021-11-16',
               '2021-11-17', '2021-11-18', '2021-11-19', '2021-11-20',
               '2021-11-21', '2021-11-22', '2021-11-23', '2021-11-24',
               '2021-11-25', '2021-11-26', '2021-11-27', '2021-11-28',
               '2021-11-29', '2021-11-30', '2021-12-01', '2021-12-02',
               '2021-12-03', '2021-12-04', '2021-12-05', '2021-12-06',
               '2021-12-07', '2021-12-08', '2021-12-09', '2021-12-10',
               '2021-12-11', '2021-12-12'],
              dtype='datetime64[ns]', freq='D')


In [161]:
print(s)
print(type(s))
print(s[3])
print(s[2:])
print(num[2:])
print(s[0:4])

0    2
1    4
2    5
3    6
4    9
dtype: int64
<class 'pandas.core.series.Series'>
6
2    5
3    6
4    9
dtype: int64
2    3
3    4
4    5
5    6
dtype: int64
0    2
1    4
2    5
3    6
dtype: int64


In [163]:
pd.Series([0,1,2],index=['a','b','c'])

a    0
b    1
c    2
dtype: int64

In [165]:
pd.Series(np.array(range(0,10))**2,index=range(0,10))

0     0
1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

In [168]:
df=pd.DataFrame({'name':['abc','def','ghi'],
                 'age':[22,24,27],
                 'occupation':['engineer','data analyst','doctor']})
df        

name  age    occupation
0  abc   22      engineer
1  def   24  data analyst
2  ghi   27        doctor

In [169]:
import numpy as np
import pandas as pd

In [170]:
marketfact_df=pd.read_csv("C:/RFILES/market_fact.csv")

In [172]:
marketfact_df

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
...        ...      ...       ...        ...        ...       ...   
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0                 23   -30.51           3.60                 0.56  
1                 13     4.56           0.93                 0.54  
2                 26  1148.90           2.50                 0.59  
3                 43   729.34          14.30                 0.37  
4                 35  1219.87          26.30                 0.38  
...              ...      ...            ...                  ...  
8394              28   374.63           7.69                 0.59  
8395              20   -74.03           6.92                 0.37  
8396              39   -70.85           5.35                 0.40  
8397              23   565.34          30.00                 0.62  
8398              47   131.39           4.86                 0.38  

[8399 rows x 10 columns]

In [173]:
type(marketfact_df)

pandas.core.frame.DataFrame

In [175]:
marketfact_df.head()#top 5 rows.

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.81      0.01              23   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   

    Profit  Shipping_Cost  Product_Base_Margin  
0   -30.51           3.60                 0.56  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38

In [177]:
marketfact_df.tail()#bottom rows.

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity  Profit  Shipping_Cost  Product_Base_Margin  
8394              28  374.63           7.69                 0.59  
8395              20  -74.03           6.92                 0.37  
8396              39  -70.85           5.35                 0.40  
8397              23  565.34          30.00                 0.62  
8398              47  131.39           4.86                 0.38

In [178]:
#looking at datatype of each function.
marketfact_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8399 entries, 0 to 8398
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Ord_id               8399 non-null   object 
 1   Prod_id              8399 non-null   object 
 2   Ship_id              8399 non-null   object 
 3   Cust_id              8399 non-null   object 
 4   Sales                8399 non-null   float64
 5   Discount             8399 non-null   float64
 6   Order_Quantity       8399 non-null   int64  
 7   Profit               8399 non-null   float64
 8   Shipping_Cost        8399 non-null   float64
 9   Product_Base_Margin  8336 non-null   float64
dtypes: float64(5), int64(1), object(4)
memory usage: 656.3+ KB


In [179]:
marketfact_df.describe()

Sales     Discount  Order_Quantity        Profit  Shipping_Cost  \
count   8399.000000  8399.000000     8399.000000   8399.000000    8399.000000   
mean    1775.878179     0.049671       25.571735    181.184424      12.838557   
std     3585.050525     0.031823       14.481071   1196.653371      17.264052   
min        2.240000     0.000000        1.000000 -14140.700000       0.490000   
25%      143.195000     0.020000       13.000000    -83.315000       3.300000   
50%      449.420000     0.050000       26.000000     -1.500000       6.070000   
75%     1709.320000     0.080000       38.000000    162.750000      13.990000   
max    89061.050000     0.250000       50.000000  27220.690000     164.730000   

       Product_Base_Margin  
count          8336.000000  
mean              0.512513  
std               0.135589  
min               0.350000  
25%               0.380000  
50%               0.520000  
75%               0.590000  
max               0.850000

In [181]:
marketfact_df.columns

Index(['Ord_id', 'Prod_id', 'Ship_id', 'Cust_id', 'Sales', 'Discount',
       'Order_Quantity', 'Profit', 'Shipping_Cost', 'Product_Base_Margin'],
      dtype='object')

In [183]:
marketfact_df.shape# gives(no. of rows,no. of columns)

(8399, 10)

In [184]:
marketfact_df.values#extracting the values

array([['Ord_5446', 'Prod_16', 'SHP_7609', ..., -30.51, 3.6, 0.56],
       ['Ord_5406', 'Prod_13', 'SHP_7549', ..., 4.56, 0.93, 0.54],
       ['Ord_5446', 'Prod_4', 'SHP_7610', ..., 1148.9, 2.5, 0.59],
       ...,
       ['Ord_5388', 'Prod_6', 'SHP_7524', ..., -70.85, 5.35, 0.4],
       ['Ord_5348', 'Prod_15', 'SHP_7469', ..., 565.34, 30.0, 0.62],
       ['Ord_5459', 'Prod_6', 'SHP_7628', ..., 131.39, 4.86, 0.38]],
      dtype=object)

In [185]:
marketfact_df.sort_values(by="Profit").head()

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
6952  Ord_5452  Prod_17  SHP_7621  Cust_1796  18888.00      0.09   
4772  Ord_5047  Prod_17  SHP_7043  Cust_1714  19707.20      0.04   
84    Ord_5232  Prod_17  SHP_7306  Cust_1758  21366.51      0.00   
5454  Ord_3903  Prod_14  SHP_5417  Cust_1334   3457.99      0.05   
5968  Ord_3073  Prod_14  SHP_4267  Cust_1142   3550.28      0.06   

      Order_Quantity    Profit  Shipping_Cost  Product_Base_Margin  
6952               3 -14140.70          24.49                 0.39  
4772               3 -12558.00          24.49                 0.39  
84                 3 -11984.40          24.49                 0.39  
5454               1 -11861.46          24.49                 0.37  
5968               1 -11769.17          24.49                 0.37

In [4]:
import pandas as pd
import numpy as np
marketfact_df=pd.read_csv("C:/RFILES/market_fact.csv")
marketfact_df.sort_values(by="Profit",ascending=False).head()

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
2738  Ord_3084  Prod_17  SHP_4279  Cust_1151  89061.05      0.00   
385   Ord_3707  Prod_17  SHP_5136  Cust_1307  28359.40      0.05   
2253  Ord_3143  Prod_14  SHP_4362  Cust_1170  28664.52      0.09   
4399  Ord_4614  Prod_14  SHP_6423  Cust_1571  29884.60      0.05   
6765  Ord_5186  Prod_17  SHP_7247  Cust_1763  26095.13      0.03   

      Order_Quantity    Profit  Shipping_Cost  Product_Base_Margin  
2738              13  27220.69          24.49                 0.39  
385               49  14440.39          24.49                 0.37  
2253              50  13340.26          24.49                 0.37  
4399              49  12748.86          24.49                 0.44  
6765              35  12606.81          55.30                 0.40

In [5]:
marketfact_df.sort_values(by="Profit",ascending=False)

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
2738  Ord_3084  Prod_17  SHP_4279  Cust_1151  89061.05      0.00   
385   Ord_3707  Prod_17  SHP_5136  Cust_1307  28359.40      0.05   
2253  Ord_3143  Prod_14  SHP_4362  Cust_1170  28664.52      0.09   
4399  Ord_4614  Prod_14  SHP_6423  Cust_1571  29884.60      0.05   
6765  Ord_5186  Prod_17  SHP_7247  Cust_1763  26095.13      0.03   
...        ...      ...       ...        ...       ...       ...   
5968  Ord_3073  Prod_14  SHP_4267  Cust_1142   3550.28      0.06   
5454  Ord_3903  Prod_14  SHP_5417  Cust_1334   3457.99      0.05   
84    Ord_5232  Prod_17  SHP_7306  Cust_1758  21366.51      0.00   
4772  Ord_5047  Prod_17  SHP_7043  Cust_1714  19707.20      0.04   
6952  Ord_5452  Prod_17  SHP_7621  Cust_1796  18888.00      0.09   

      Order_Quantity    Profit  Shipping_Cost  Product_Base_Margin  
2738              13  27220.69          24.49                 0.39  
385               49  14440.39          24.49                 0.37  
2253              50  13340.26          24.49                 0.37  
4399              49  12748.86          24.49                 0.44  
6765              35  12606.81          55.30                 0.40  
...              ...       ...            ...                  ...  
5968               1 -11769.17          24.49                 0.37  
5454               1 -11861.46          24.49                 0.37  
84                 3 -11984.40          24.49                 0.39  
4772               3 -12558.00          24.49                 0.39  
6952               3 -14140.70          24.49                 0.39  

[8399 rows x 10 columns]

In [7]:
marketfact_df.sort_values(by=["Profit","Sales"],ascending=False)

Ord_id  Prod_id   Ship_id    Cust_id     Sales  Discount  \
2738  Ord_3084  Prod_17  SHP_4279  Cust_1151  89061.05      0.00   
385   Ord_3707  Prod_17  SHP_5136  Cust_1307  28359.40      0.05   
2253  Ord_3143  Prod_14  SHP_4362  Cust_1170  28664.52      0.09   
4399  Ord_4614  Prod_14  SHP_6423  Cust_1571  29884.60      0.05   
6765  Ord_5186  Prod_17  SHP_7247  Cust_1763  26095.13      0.03   
...        ...      ...       ...        ...       ...       ...   
5968  Ord_3073  Prod_14  SHP_4267  Cust_1142   3550.28      0.06   
5454  Ord_3903  Prod_14  SHP_5417  Cust_1334   3457.99      0.05   
84    Ord_5232  Prod_17  SHP_7306  Cust_1758  21366.51      0.00   
4772  Ord_5047  Prod_17  SHP_7043  Cust_1714  19707.20      0.04   
6952  Ord_5452  Prod_17  SHP_7621  Cust_1796  18888.00      0.09   

      Order_Quantity    Profit  Shipping_Cost  Product_Base_Margin  
2738              13  27220.69          24.49                 0.39  
385               49  14440.39          24.49                 0.37  
2253              50  13340.26          24.49                 0.37  
4399              49  12748.86          24.49                 0.44  
6765              35  12606.81          55.30                 0.40  
...              ...       ...            ...                  ...  
5968               1 -11769.17          24.49                 0.37  
5454               1 -11861.46          24.49                 0.37  
84                 3 -11984.40          24.49                 0.39  
4772               3 -12558.00          24.49                 0.39  
6952               3 -14140.70          24.49                 0.39  

[8399 rows x 10 columns]

In [9]:
marketfact_df[1:7]#selecting rows from 1 to 6.

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.27      0.01              13   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   
5  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.02      0.03              23   
6    Ord_31  Prod_12    SHP_41    Cust_26    14.76      0.01               5   

    Profit  Shipping_Cost  Product_Base_Margin  
1     4.56           0.93                 0.54  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38  
5   -47.64           6.15                 0.37  
6     1.32           0.50                 0.36

In [11]:
marketfact_df[2::2].head()#selecting alternate rows starting from index=2.

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
2   Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
4   Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   
6     Ord_31  Prod_12    SHP_41    Cust_26    14.76      0.01               5   
8   Ord_4725  Prod_13  SHP_6593  Cust_1641   162.00      0.01              33   
10  Ord_4743   Prod_2  SHP_6615  Cust_1641  4072.01      0.01              43   

     Profit  Shipping_Cost  Product_Base_Margin  
2   1148.90           2.50                 0.59  
4   1219.87          26.30                 0.38  
6      1.32           0.50                 0.36  
8     45.84           0.71                 0.52  
10  1675.98           0.99                 0.56

In [12]:
marketfact_df[3::4].head()

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
3   Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
7   Ord_4725   Prod_4  SHP_6593  Cust_1641  3410.1575      0.10   
11  Ord_1925   Prod_6  SHP_2637   Cust_708   465.9000      0.05   
15  Ord_2280   Prod_5  SHP_3114   Cust_839   460.6900      0.06   
19   Ord_996  Prod_13  SHP_1378   Cust_371    41.9700      0.05   

    Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
3               43   729.34          14.30                 0.37  
7               48  1137.91           0.99                 0.55  
11              38    79.34           4.86                 0.38  
15              48  -103.48           7.29                 0.45  
19              12   -37.03           4.20                 0.56

select columns

In [15]:
sales_1=marketfact_df['Profit']
sales_1.head()

0     -30.51
1       4.56
2    1148.90
3     729.34
4    1219.87
Name: Profit, dtype: float64

In [16]:
sales_2=marketfact_df.Sales
sales_2.head()

0     136.81
1      42.27
2    4701.69
3    2337.89
4    4233.15
Name: Sales, dtype: float64

In [19]:
#selecting multiple columns
multiple_columns=marketfact_df[['Cust_id','Sales','Profit']].head()
multiple_columns

Cust_id    Sales   Profit
0  Cust_1818   136.81   -30.51
1  Cust_1818    42.27     4.56
2  Cust_1818  4701.69  1148.90
3  Cust_1818  2337.89   729.34
4  Cust_1818  4233.15  1219.87

In [20]:
type(multiple_columns)

pandas.core.frame.DataFrame

In [23]:
multiple_columns[2]###error as pandas does not know whether it is 2nd row or 3rd index so we have to explicitly define by indexing.

KeyError: 2

In [24]:
marketfact_df

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0     Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1     Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2     Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3     Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4     Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
...        ...      ...       ...        ...        ...       ...   
8394  Ord_5353   Prod_4  SHP_7479  Cust_1798  2841.4395      0.08   
8395  Ord_5411   Prod_6  SHP_7555  Cust_1798   127.1600      0.10   
8396  Ord_5388   Prod_6  SHP_7524  Cust_1798   243.0500      0.02   
8397  Ord_5348  Prod_15  SHP_7469  Cust_1798  3872.8700      0.03   
8398  Ord_5459   Prod_6  SHP_7628  Cust_1798   603.6900      0.00   

      Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0                 23   -30.51           3.60                 0.56  
1                 13     4.56           0.93                 0.54  
2                 26  1148.90           2.50                 0.59  
3                 43   729.34          14.30                 0.37  
4                 35  1219.87          26.30                 0.38  
...              ...      ...            ...                  ...  
8394              28   374.63           7.69                 0.59  
8395              20   -74.03           6.92                 0.37  
8396              39   -70.85           5.35                 0.40  
8397              23   565.34          30.00                 0.62  
8398              47   131.39           4.86                 0.38  

[8399 rows x 10 columns]

In [26]:
marketfact_df1=marketfact_df[0:10]
marketfact_df1

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
0  Ord_5446  Prod_16  SHP_7609  Cust_1818   136.8100      0.01   
1  Ord_5406  Prod_13  SHP_7549  Cust_1818    42.2700      0.01   
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.6900      0.00   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
5  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.0200      0.03   
6    Ord_31  Prod_12    SHP_41    Cust_26    14.7600      0.01   
7  Ord_4725   Prod_4  SHP_6593  Cust_1641  3410.1575      0.10   
8  Ord_4725  Prod_13  SHP_6593  Cust_1641   162.0000      0.01   
9  Ord_4725   Prod_6  SHP_6593  Cust_1641    57.2200      0.07   

   Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
0              23   -30.51           3.60                 0.56  
1              13     4.56           0.93                 0.54  
2              26  1148.90           2.50                 0.59  
3              43   729.34          14.30                 0.37  
4              35  1219.87          26.30                 0.38  
5              23   -47.64           6.15                 0.37  
6               5     1.32           0.50                 0.36  
7              48  1137.91           0.99                 0.55  
8              33    45.84           0.71                 0.52  
9               8   -27.72           6.60                 0.37

In [28]:
marketfact_df1.iloc[2,4]# correspond to 3rd and 5th column.

4701.69

marketfact_df1.iloc[2,4]

In [30]:
marketfact_df1.iloc[2] #corresponds to a single row and all columns. 

Ord_id                  Ord_5446
Prod_id                   Prod_4
Ship_id                 SHP_7610
Cust_id                Cust_1818
Sales                    4701.69
Discount                     0.0
Order_Quantity                26
Profit                    1148.9
Shipping_Cost                2.5
Product_Base_Margin         0.59
Name: 2, dtype: object

In [32]:
marketfact_df1.iloc[[3,7,8]]#multiple rows

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.8900      0.09   
7  Ord_4725   Prod_4  SHP_6593  Cust_1641  3410.1575      0.10   
8  Ord_4725  Prod_13  SHP_6593  Cust_1641   162.0000      0.01   

   Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
3              43   729.34          14.30                 0.37  
7              48  1137.91           0.99                 0.55  
8              33    45.84           0.71                 0.52

In [34]:
marketfact_df1.iloc[4:8]#multiple rows and 8th row not included.

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.1500      0.08   
5  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.0200      0.03   
6    Ord_31  Prod_12    SHP_41    Cust_26    14.7600      0.01   
7  Ord_4725   Prod_4  SHP_6593  Cust_1641  3410.1575      0.10   

   Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
4              35  1219.87          26.30                 0.38  
5              23   -47.64           6.15                 0.37  
6               5     1.32           0.50                 0.36  
7              48  1137.91           0.99                 0.55

In [37]:
marketfact_df1.iloc[:,2]#selecting a single column here third column.

0    SHP_7609
1    SHP_7549
2    SHP_7610
3    SHP_7625
4    SHP_7664
5    SHP_7608
6      SHP_41
7    SHP_6593
8    SHP_6593
9    SHP_6593
Name: Ship_id, dtype: object

In [39]:
marketfact_df1.iloc[:,3:8]#before , represents rows and after , represents columns.

Cust_id      Sales  Discount  Order_Quantity   Profit
0  Cust_1818   136.8100      0.01              23   -30.51
1  Cust_1818    42.2700      0.01              13     4.56
2  Cust_1818  4701.6900      0.00              26  1148.90
3  Cust_1818  2337.8900      0.09              43   729.34
4  Cust_1818  4233.1500      0.08              35  1219.87
5  Cust_1818   164.0200      0.03              23   -47.64
6    Cust_26    14.7600      0.01               5     1.32
7  Cust_1641  3410.1575      0.10              48  1137.91
8  Cust_1641   162.0000      0.01              33    45.84
9  Cust_1641    57.2200      0.07               8   -27.72

In [40]:
marketfact_df1.iloc[3:6,2:5]#(rows,columns)

Ship_id    Cust_id    Sales
3  SHP_7625  Cust_1818  2337.89
4  SHP_7664  Cust_1818  4233.15
5  SHP_7608  Cust_1818   164.02

In [44]:
#label based indexing
marketfact_df1.loc[2,'Sales']# prints 2nd label row and sales column.

4701.69

In [45]:
marketfact_df1.loc[5]#prints 5th label row

Ord_id                  Ord_5446
Prod_id                   Prod_6
Ship_id                 SHP_7608
Cust_id                Cust_1818
Sales                     164.02
Discount                    0.03
Order_Quantity                23
Profit                    -47.64
Shipping_Cost               6.15
Product_Base_Margin         0.37
Name: 5, dtype: object

In [46]:
marketfact_df1.loc[[5,6,7]]

Ord_id  Prod_id   Ship_id    Cust_id      Sales  Discount  \
5  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.0200      0.03   
6    Ord_31  Prod_12    SHP_41    Cust_26    14.7600      0.01   
7  Ord_4725   Prod_4  SHP_6593  Cust_1641  3410.1575      0.10   

   Order_Quantity   Profit  Shipping_Cost  Product_Base_Margin  
5              23   -47.64           6.15                 0.37  
6               5     1.32           0.50                 0.36  
7              48  1137.91           0.99                 0.55

In [47]:
marketfact_df1.loc[2:5]

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   
5  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.02      0.03              23   

    Profit  Shipping_Cost  Product_Base_Margin  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38  
5   -47.64           6.15                 0.37

In [48]:
marketfact_df1.loc[2:5,]

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   
5  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.02      0.03              23   

    Profit  Shipping_Cost  Product_Base_Margin  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38  
5   -47.64           6.15                 0.37

In [49]:
marketfact_df1.loc[2:5, : ]

Ord_id  Prod_id   Ship_id    Cust_id    Sales  Discount  Order_Quantity  \
2  Ord_5446   Prod_4  SHP_7610  Cust_1818  4701.69      0.00              26   
3  Ord_5456   Prod_6  SHP_7625  Cust_1818  2337.89      0.09              43   
4  Ord_5485  Prod_17  SHP_7664  Cust_1818  4233.15      0.08              35   
5  Ord_5446   Prod_6  SHP_7608  Cust_1818   164.02      0.03              23   

    Profit  Shipping_Cost  Product_Base_Margin  
2  1148.90           2.50                 0.59  
3   729.34          14.30                 0.37  
4  1219.87          26.30                 0.38  
5   -47.64           6.15                 0.37

In [ ]:
#replacing rows table with anyone values from a column like here we replace ORDER_ID.
marketfact_df1.set_index('Ord_id',inplace=True)
marketfact_df1.head()

KeyError: "None of ['Ord_id'] are in the columns"